### ISSUE TITLE
General Question - Not able to open forms with future dates not sure if you have to wait until the day or if that could be left off?

### ISSUE THREAD

**Issue by devmatics-issues** [devmatics/clockwork-issues#16]
# Details
**Category:** General Question

**Short Description:** Not able to open forms with future dates not sure if you have to wait until the day or if that could be left off?

**Full Description:**

**Attachments:**
![](https://www.clockworksafety.com/wp-content/uploads/formidable/4/AD93D2C5-27F9-4431-8C27-4F3B2BCE2CF2.png,https://www.clockworksafety.com/wp-content/uploads/formidable/4/BA5C5547-CE26-48E8-A81B-75DE2E4C0C5D.png,https://www.clockworksafety.com/wp-content/uploads/formidable/4/F9849CF6-13A2-47B9-B299-5CF0A1D0FD18.png)

**Priority:** Low
**User Type:** Employee (App)
**Device:** Mobile - iOS / Apple
**Browser:** Apple Safari
**Source:** https://www.clockworksafety.com/support-ticket/

**Submitted By:**
James Bromley (james@jriteam.com)
Jri

# Related Issues

- [x] https://github.com/devmatics/clockwork-app/issues/21
- [x] https://github.com/devmatics/clockwork-portal/issues/34
- [x] https://github.com/devmatics/clockwork-api/issues/26

**Comment by WardenDrew** [comment]
Notes from meeting:
Frontend to use api filters to only show forms that are available
API to change ExpiresOn to be firm expires on to hide / kill forms that are expired

**Comment by ARegalbuto** [comment]
related: #32 
This is the flip side of this issue.  We discussed adding two options for end dates: expires on is a hard block of a assignment, and due on would be a soft end of the assignment but still allow editing.  The other problem they are asking is once it is expired and no longer editable, then it no longer shows in the employees form assignment list.

**Comment by ARegalbuto** [comment]
Fixed as of 0.9.2 release
