### ISSUE TITLE
Bug - Multiple choice responses (and probably single responses) do not appear in  responses history for portal users.

### ISSUE THREAD

**Issue by devmatics-issues** [devmatics/clockwork-issues#20]
# Details
**Category:** Bug

**Short Description:** Multiple choice responses (and probably single responses) do not appear in  responses history for portal users.

**Full Description:**

**Attachments:**
![](https://www.clockworksafety.com/wp-content/uploads/formidable/4/chrome_p5S9Tn3m3l.png)

**Priority:** Medium
**User Type:** Manager (Portal)
**Device:** Desktop - Windows
**Browser:** Google Chrome
**Source:** https://www.clockworksafety.com/support-ticket/

**Submitted By:**
Clockwork Safety (admin@devmatics.io)

# Related Issues

**Comment by ARegalbuto** [comment]
Info migrated to #19
