### ISSUE TITLE
Bug - Uploaded files do not appear on submitted forms for portal users.

### ISSUE THREAD

**Issue by devmatics-issues** [devmatics/clockwork-issues#21]
# Details
**Category:** Bug

**Short Description:** Uploaded files do not appear on submitted forms for portal users.

**Full Description:**

**Attachments:**
![](https://www.clockworksafety.com/wp-content/uploads/formidable/4/chrome_YAaL3Ew6M6.png)

**Priority:** Medium
**User Type:** Manager (Portal)
**Device:** Desktop - Windows
**Browser:** Google Chrome
**Source:** https://www.clockworksafety.com/support-ticket/

**Submitted By:**
Clockwork Safety (admin@devmatics.io)

# Related Issues

**Comment by ARegalbuto** [comment]
Info migrated to #19
