### ISSUE TITLE
Bug - Manual time entries created on portal do not appear on the overall time screen.

### ISSUE THREAD

**Issue by devmatics-issues** [devmatics/clockwork-issues#23]
# Details
**Category:** Bug

**Short Description:** Manual time entries created on portal do not appear on the overall time screen.

**Full Description:**
If the portal manually adds a time entry for an employee it won't appear on the screen. It shows as being created, but it isn't displaying anything.

**Attachments:**
![](https://www.clockworksafety.com/wp-content/uploads/formidable/4/chrome_hMIsga8NBv.png,https://www.clockworksafety.com/wp-content/uploads/formidable/4/chrome_SUGAPp8rTh.png)

**Priority:** Medium
**User Type:** Manager (Portal)
**Device:** Desktop - Windows
**Browser:** Google Chrome
**Source:** https://www.clockworksafety.com/support-ticket/

**Submitted By:**
Clockwork Safety (admin@devmatics.io)

# Related Issues

**Comment by ARegalbuto** [comment]
This bug lead us to find another bug.  Going to retest tomorrow

**Comment by ARegalbuto** [comment]
retested. fixed as of 0.9.1 release
