### ISSUE TITLE
Bug - Time entires which have been denied on the portal show as being approved on the user's app.

### ISSUE THREAD

**Issue by devmatics-issues** [devmatics/clockwork-issues#24]
# Details
**Category:** Bug

**Short Description:** Time entires which have been denied on the portal show as being approved on the user's app.

**Full Description:**
If a manager denies a time entry it will show as denied on the portal, but it won't show as denied on the user's app.

**Attachments:**
![](https://www.clockworksafety.com/wp-content/uploads/formidable/4/chrome_kcrUObgBZo.png)

**Priority:** High
**User Type:** All (Portal + App)
**Device:** Desktop - Windows
**Browser:** Google Chrome
**Source:** https://www.clockworksafety.com/support-ticket/

**Submitted By:**
Clockwork Safety (admin@devmatics.io)

# Related Issues

- [x] https://github.com/devmatics/clockwork-app/issues/11

**Comment by ARegalbuto** [comment]
fixed with the 0.9.1 release
