### ISSUE TITLE
Bug - Form Bug

### ISSUE THREAD

**Issue by devmatics-io** [devmatics/clockwork-issues#32]
# Details
**Category:** Bug

**Short Description:** Form Bug

**Full Description:**
Last week I missed doing a few forms and they still appear today as I need to do them but they are not allowing me to click them to complete as of today

**Attachments:**
![](https://www.clockworksafety.com/wp-content/uploads/formidable/4/CWS-Form-Bug.png)

**Priority:** Medium
**User Type:** All (Portal + App)
**Device:** Desktop - Windows
**Browser:** Google Chrome
**Source:** https://www.clockworksafety.com/support-ticket/

**Submitted By:**
Hunter Hiatt (hunter@clockworksafety.com)
Clockwork Safety

# Related Issues

- [x] https://github.com/devmatics/clockwork-app/issues/33

**Comment by ARegalbuto** [comment]
Need to change expired/past due to a "soft error" 
@WardenDrew is going to fix it in API

![image](https://user-images.githubusercontent.com/92471253/146463932-f6bf626a-fe42-4b50-9cf1-453e1dcb6a91.png)

**Comment by ARegalbuto** [comment]
This is resolved
