### ISSUE TITLE
Enhancement - Forms Submission Reports should show employee name

### ISSUE THREAD

**Issue by ARegalbuto** [devmatics/clockwork-issues#34]
**Is your feature request related to a problem? Please describe.**
Forms submission reports currently show the ID number of the employee that submitted it. It does not show the name of the employee that submitted it. The name would be useful in validating everyone has submitted the form.

![image](https://user-images.githubusercontent.com/92471253/142706555-aea17015-82af-48c5-afd3-17640140d1af.png)

**Describe the solution you'd like**
Change ID number to Employee Name.

**Describe alternatives you've considered**
Do Nothing 

**Additional context**
Approved by @alexdwhite , Entered in issues so stakeholders can track the enhancement.  Coping to portal.

- [x] https://github.com/devmatics/clockwork-portal/issues/61
- [x] https://github.com/devmatics/clockwork-api/issues/36

**Comment by WardenDrew** [comment]
Closing as the reports area will be using MyDBR
