### ISSUE TITLE
Admin Forms Multi-Select Answer does not show a Required toggle button

### ISSUE THREAD

**Issue by ARegalbuto** [devmatics/clockwork-issues#39]
**Describe the bug**
When creating a question using the Multi-Select Answer, the required toggle button disappears from the question bar. 

**To Reproduce**

View Loom:
https://www.loom.com/share/45752db435754423a57e9a8ed566d6f7
- [x] https://github.com/devmatics/clockwork-portal/issues/66

**Comment by WardenDrew** [comment]
https://github.com/devmatics/clockwork-portal/issues/66#issuecomment-974566594
