### ISSUE TITLE
Bug - "Forms" page not loading

### ISSUE THREAD

**Issue by devmatics-issues** [devmatics/clockwork-issues#42]
# Details
**Category:** Bug

**Short Description:** "Forms" page not loading

**Full Description:**
The “Forms” page on the Admin's Portal does not seem to be loading for me. (I’m logging in using the Support@clockworksafety.com username.) I was wondering if this is a problem I’m experiencing alone due to a possible poor connection, or if there is another potential problem going on. I wanted to report it in case it could be the latter option. Thank you!

**Attachments:**
![](https://www.clockworksafety.com/wp-content/uploads/formidable/4/Screenshot-6.png)

**Priority:** Medium
**User Type:** All (Portal + App)
**Device:** Desktop - Windows
**Browser:** Google Chrome
**Source:** https://www.clockworksafety.com/support-ticket/

**Submitted By:**
Mia Nelson (mia.nelson232@gmail.com)
ClockworkSafety

# Related Issues

**Comment by WardenDrew** [comment]
From what I could tell triaging this during our meeting yesterday, this is just on her end. @alexdwhite do you want me to reach out to her direct via email and see if the issue is still ongoing?
