### ISSUE TITLE
Bug - New User Invitation not working

### ISSUE THREAD

**Issue by devmatics-issues** [devmatics/clockwork-issues#43]
# Details
**Category:** Bug

**Short Description:** New User Invitation not working

**Full Description:**
A few times recently when we try to add a new user it has been saying "create operation on a record failed" and it doesn't let us add them

**Attachments:**
![](https://www.clockworksafety.com/wp-content/uploads/formidable/4/create-Account-bug.png)

**Priority:** High
**User Type:** All (Portal + App)
**Device:** Desktop - Windows
**Browser:** Google Chrome
**Source:** https://www.clockworksafety.com/support-ticket/

**Submitted By:**
Hunter Hiatt (hunterhiatt72@clockworksafety.com)
Clockwork

# Related Issues

- [ ] https://github.com/devmatics/clockwork-api/issues/37

**Comment by WardenDrew** [comment]
@alexdwhite we need to overhaul user registration like we talked about last. It might be worth pushing our deploy to address this

**Comment by alexdwhite** [comment]
@WardenDrew It was his password requirement.  We can get this addressed on the next release.  I still want to get a deploy this week.
