### ISSUE TITLE
Bug - Log in not loading

### ISSUE THREAD

**Issue by devmatics-io** [devmatics/clockwork-issues#44]
# Details
**Category:** Bug

**Short Description:** Log in not loading

**Full Description:**
When out employees went to app.clockworksafety.com it just showed a picture and no log in box

**Attachments:**
![](https://www.clockworksafety.com/wp-content/uploads/formidable/4/C412DD56-1168-4896-BEB1-61AFAE48E26E.jpeg)

**Priority:** Medium
**User Type:** Employee (App)
**Device:** Desktop - Windows
**Browser:** Google Chrome
**Source:** https://www.clockworksafety.com/support-ticket/

**Submitted By:**
Hunter Hiatt (hunter@jriteam.com)
Jri

# Related Issues

**Comment by ARegalbuto** [comment]
@alexdwhite I have never seen this issue when using the app.  Obviously the app is more broken at the moment.  But even the pic they attached contradicts what the bug description is.  Should I just close this?

**Comment by alexdwhite** [comment]
Temporary bug, gone now.
