### ISSUE TITLE
Feature Request - Could you make it so that the employees receive notifications for messages that are sent?

### ISSUE THREAD

**Issue by devmatics-issues** [devmatics/clockwork-issues#46]
# Details
**Category:** Feature Request

**Short Description:** Could you make it so that the employees receive notifications for messages that are sent?

**Full Description:**
When messages are sent employees do not receive notifications.

**Attachments:**
![]()

**Priority:** High
**User Type:** Manager (Portal)
**Device:** Desktop - Windows
**Browser:** Google Chrome
**Source:** https://www.clockworksafety.com/support-ticket/

**Submitted By:**
William Cardon (william@jriteam.com)
JRI Insurance

# Related Issues

**Comment by alexdwhite** [comment]
@ARegalbuto can you relay to William that this we be part of our Mobile app (iOS/Android) release which starts development in January 2022.

**Comment by ARegalbuto** [comment]
William was notified via email.  Closing feature request.
