### ISSUE TITLE
Bug - Forms Just Spinning and Not loading

### ISSUE THREAD

**Issue by devmatics-issues** [devmatics/clockwork-issues#53]
# Details
**Category:** Bug

**Short Description:** Forms Just Spinning and Not loading

**Full Description:**
When I go to open Forms on the admin side they just sit there and spin and do not load. the feature is unsuable

**Attachments:**
![](https://www.clockworksafety.com/wp-content/uploads/formidable/4/Form-Screen.png)

**Priority:** High
**User Type:** Manager (Portal)
**Device:** Desktop - Windows
**Browser:** Google Chrome
**Source:** https://www.clockworksafety.com/support-ticket/

**Submitted By:**
Hunter Hiatt (hunter@clockworksafety.com)
CWS

# Related Issues
- [ ] https://www.github.com/devmatics/clockwork-portal/issues/111

**Comment by alexdwhite** [comment]
We fixed the data as a temporary thing, but will need related work to prevent these issues in future.  
Basically a Form was started but no Revision was created.  Null reference to sub object
