### ISSUE TITLE
Bug - Reports Not working

### ISSUE THREAD

**Issue by devmatics-io** [devmatics/clockwork-issues#54]
# Details
**Category:** Bug

**Short Description:** Reports Not working

**Full Description:**
THe reports section shows they are there but there is no way to pull a report it just gives me random letters

**Attachments:**
![](https://www.clockworksafety.com/wp-content/uploads/formidable/4/Reports-Not-Working.png)

**Priority:** High
**User Type:** Manager (Portal)
**Device:** Desktop - Windows
**Browser:** Google Chrome
**Source:** https://www.clockworksafety.com/support-ticket/

**Submitted By:**
Hunter Hiatt (hunter@clockworksafety.com)
CWS

# Related Issues

**Comment by ARegalbuto** [comment]
Not all reports are working yet.  We are still building some of the program.  We will be removing any reports that do not currently work.

**Comment by ARegalbuto** [comment]
All available reports are currently working.
