### ISSUE TITLE
Website Issue - Uploading files to create forms.

### ISSUE THREAD

**Issue by devmatics-io** [devmatics/clockwork-issues#55]
# Details
**Category:** Website Issue

**Short Description:** Uploading files to create forms.

**Full Description:**
When I try to create a form by uploading a file it won't give me any options to view or select files to upload.

**Attachments:**
![]()

**Priority:** High
**User Type:** Manager (Portal)
**Device:** Desktop - Windows
**Browser:** Google Chrome
**Source:** https://www.clockworksafety.com/support-ticket/

**Submitted By:**
William Cardon (william@jriteam.com)
JRI Insurance

# Related Issues

**Comment by ARegalbuto** [comment]
Emailed to clarify the problem.  Forms is not designed to create a form from a pre-existing document currently.

**Comment by ARegalbuto** [comment]
@alexdwhite should I close this?  This is not a feature we are planning to include correct?

**Comment by alexdwhite** [comment]
This is not a feature that can be made. We WILL have the ability to upload files into forms later.
